spring.datasource.url=jdbc:postgresql://localhost:5432/resource_allocation_db
spring.datasource.username=postgres
spring.datasource.password=095107
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

gemini.api.key=${GEMINI_API_KEY:}
gemini.api.model=gemini-2.5-flash
